In [4]:
''' Create an array using numpy library '''
import numpy as np
a=np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
np.linspace(0,10,5,endpoint=False)

array([0., 2., 4., 6., 8.])

In [8]:
np.linspace(0,10,5,endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
np.logspace(1,3,3)

array([  10.,  100., 1000.])

In [16]:
np.logspace(0,10)

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [18]:
b=[[90,10,30],[80,70,60]]
np.shape(b)

(2, 3)

In [20]:
np.reshape(b,(3,2))

array([[90, 10],
       [30, 80],
       [70, 60]])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
from numpy import random
x = random.randint(10,21)
print(x)

15


In [32]:
c=np.array([[10,20,30],[40,50,60]])
print(c[0,1])

20


In [34]:
d=np.array([82,123,1,76,92,0])
print(d[2:])

[ 1 76 92  0]


In [36]:
print(d[0:6:-1])

[]


In [38]:
e=d.copy()
print(e)

[ 82 123   1  76  92   0]


In [40]:
f=d.view()
print(f)

[ 82 123   1  76  92   0]


In [42]:
f[1]=2
print(f)
print(d)

[82  2  1 76 92  0]
[82  2  1 76 92  0]


In [44]:
np.sort(b,axis=0)

array([[80, 10, 30],
       [90, 70, 60]])

In [46]:
np.sort(b,axis=1)

array([[10, 30, 90],
       [60, 70, 80]])

In [48]:
np.searchsorted(d,92)

6

In [50]:
g=np.array([10,100,10])
np.where(a==30)

(array([], dtype=int64),)

In [52]:
h=np.array([1,2,3,4,5,6,7,8,9,10])
np.split(h,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [54]:
np.split(h,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [56]:
np.array_split(h,3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [58]:
i=np.array([[1,9,3],[2,7,9]])
j=np.array([[4,5,6],[7,4,2]])
np.concatenate((i,j))

array([[1, 9, 3],
       [2, 7, 9],
       [4, 5, 6],
       [7, 4, 2]])

In [62]:
np.concatenate((i,j),axis=0)

array([[1, 9, 3],
       [2, 7, 9],
       [4, 5, 6],
       [7, 4, 2]])

In [64]:
np.concatenate((i,j),axis=1)

array([[1, 9, 3, 4, 5, 6],
       [2, 7, 9, 7, 4, 2]])

In [232]:
np.add(i,j)

array([[ 5, 14,  9],
       [ 9, 11, 11]])

In [236]:
np.subtract(i,j)

array([[-3,  4, -3],
       [-5,  3,  7]])

In [237]:
np.multiply(i,j)

array([[ 4, 45, 18],
       [14, 28, 18]])

In [238]:
np.divide(i,j)

array([[0.25      , 1.8       , 0.5       ],
       [0.28571429, 1.75      , 4.5       ]])

In [239]:
np.mod(i,j)

array([[1, 4, 3],
       [2, 3, 1]])

In [240]:
np.amin(i)

1

In [241]:
np.mean(i)

5.166666666666667

In [242]:
np.median(i)

5.0

In [243]:
np.var(i)

10.805555555555555

In [246]:
np.std(i)

3.2871804872193366

In [68]:
e=np.array([10,20,30])
f=np.array([1,2,3])
np.add(e,f)

array([11, 22, 33])

In [72]:
np.power(e,f)

array([   10,   400, 27000])

In [80]:
np.reciprocal(e.astype(float))

array([0.1       , 0.05      , 0.03333333])