In [80]:
import numpy as p

In [82]:
from numpy import poly1d
p=poly1d([3,6,8])
print(p)

   2
3 x + 6 x + 8


In [84]:
p.r

array([-1.+1.29099445j, -1.-1.29099445j])

In [86]:
p

poly1d([3, 6, 8])

In [88]:
p1=poly1d([1,2,3],variable='y')
print(p1)

   2
1 y + 2 y + 3


In [90]:
print(p.integ(k=6)) 

   3     2
1 x + 3 x + 8 x + 6


In [92]:
print(p.deriv())  

 
6 x + 6


In [94]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
import scipy.special
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [96]:
x=3
scipy.special.exp10(x)

1000.0

In [98]:
x=3
scipy.special.exp2(x)

8.0

In [20]:
d=30  
m=10  
s=50  
scipy.special.radian(d,m,s)


0.5267500645255109

In [22]:
print("sin(30)=",scipy.special.sindg(30))
print("cos(30)=",scipy.special.cosdg(30))
print("tan(30)=",scipy.special.tandg(30))

sin(30)= 0.49999999999999994
cos(30)= 0.8660254037844387
tan(30)= 0.5773502691896256


In [100]:
scipy.special.perm(5,2)

20.0

In [102]:
scipy.special.comb(5,2)

10.0

In [26]:
def f(x):
    return x**2
f(3)

9

In [28]:
g=lambda x,y:x*y
g(2,3)

6

In [30]:
h=lambda x,y:x**2+2*x*y+y**2
h(1,2)

9

In [32]:
from scipy import linalg
A1=np.array([[1,2],[3,4]])
linalg.det(A1)

-2.0

In [34]:
from scipy import linalg
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
EV,EW=linalg.eig(A)   # eigen value, eigen vectors
EV

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -8.58274334e-16+0.j])

In [38]:
EW

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [106]:
import numpy as np
A1=np.array([[1,2],[3,4]])
linalg.inv(A1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [110]:
invA= linalg.inv(A1)
I = A1.dot(invA)
print(np.around(I))

[[1. 0.]
 [0. 1.]]


In [48]:
import scipy.fftpack
import numpy as np
a=np.array([1,5,6,14,25,40])
a

array([ 1,  5,  6, 14, 25, 40])

In [50]:
y=scipy.fftpack.fft(a)
y

array([ 91. -0.j        ,  -6.+46.7653718j , -23.+13.85640646j,
       -27. -0.j        , -23.-13.85640646j,  -6.-46.7653718j ])

In [52]:
invy=scipy.fftpack.ifft(a)
invy

array([15.16666667-0.j        , -1.        -7.79422863j,
       -3.83333333-2.30940108j, -4.5       -0.j        ,
       -3.83333333+2.30940108j, -1.        +7.79422863j])

In [118]:
from scipy.stats import norm
x_norm=norm.rvs(size=500)
print(type(x_norm))

<class 'numpy.ndarray'>


In [124]:
norm.mean(),norm.std(),norm.var()

(0.0, 1.0, 1.0)

In [56]:
from scipy.stats.mstats import gmean
g=gmean([1,5,20])
print('geometric mean=',g)

geometric mean= 4.641588833612778


In [58]:
from scipy.stats.mstats import hmean
h=hmean([1,5,20])
print('harmonic mean=',h)

harmonic mean= 2.4


In [60]:
from scipy import stats
arr1=np.array([1,3,15,11,9,3])
print("arithmetic mode=",stats.mode(arr1))

arithmetic mode= ModeResult(mode=3, count=2)


In [62]:
scipy.constants.find()


['Angstrom star',
 'Avogadro constant',
 'Bohr magneton',
 'Bohr magneton in Hz/T',
 'Bohr magneton in K/T',
 'Bohr magneton in eV/T',
 'Bohr magneton in inverse meter per tesla',
 'Bohr radius',
 'Boltzmann constant',
 'Boltzmann constant in Hz/K',
 'Boltzmann constant in eV/K',
 'Boltzmann constant in inverse meter per kelvin',
 'Compton wavelength',
 'Cu x unit',
 'Faraday constant',
 'Fermi coupling constant',
 'Hartree energy',
 'Hartree energy in eV',
 'Josephson constant',
 'Loschmidt constant (273.15 K, 100 kPa)',
 'Loschmidt constant (273.15 K, 101.325 kPa)',
 'Mo x unit',
 'Newtonian constant of gravitation',
 'Newtonian constant of gravitation over h-bar c',
 'Planck constant',
 'Planck constant in eV/Hz',
 'Planck length',
 'Planck mass',
 'Planck mass energy equivalent in GeV',
 'Planck temperature',
 'Planck time',
 'Rydberg constant',
 'Rydberg constant times c in Hz',
 'Rydberg constant times hc in J',
 'Rydberg constant times hc in eV',
 'Sackur-Tetrode constant (1 K, 

In [64]:
scipy.constants.pi

3.141592653589793

In [142]:
scipy.constants.value("Planck constant")

6.62607015e-34

In [156]:
scipy.constants.value("speed of light in vacuum")

299792458.0

In [164]:
scipy.constants.value("Newtonian constant of gravitation")

6.6743e-11